name: Pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  matrix:
    name: matrix
    runs-on: ubuntu-latest
    outputs:
      gomod: ${{ steps.gomod.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: gomod
        run: |
          matrix=$(find . -type f -name "go.mod" -print0 | xargs -0 -n1 dirname | sort --unique | jq -R -s -c 'split("\n")[:-1]')
          echo "${matrix}"
          echo "::set-output name=matrix::${matrix}"
  lint:
    name: lint
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gomod: ${{ fromJson(needs.matrix.outputs.gomod) }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: posh-sandbox
      - uses: actions/checkout@v3
        with:
          path: posh
          repository: 'foomo/posh'
      - uses: actions/checkout@v3
        with:
          path: posh-providers
          repository: 'foomo/posh-providers'
      - uses: actions/setup-go@v3
        working-directory: posh-sandbox/${{ matrix.gomod }}
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        working-directory: posh-sandbox/${{ matrix.gomod }}
      - run: go test -v ./...
        working-directory: posh-sandbox/${{ matrix.gomod }}
